/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor */

#ifndef _Included_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor
#define _Included_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor
 * Method:    startTrack
 * Signature: ([BIIILjava/util/List;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor_startTrack
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jobject, jstring);

/*
 * Class:     com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor
 * Method:    trackFaces
 * Signature: ([BIII[I[I)Lcom/calculator/liuxuncheng/emotiontracker/FaceTrackArgs;
 */
JNIEXPORT jobject JNICALL Java_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor_trackFaces
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
