/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor_OnFacesDetectedListener */

#ifndef _Included_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor_OnFacesDetectedListener
#define _Included_com_calculator_liuxuncheng_emotiontracker_FaceTrackProccesor_OnFacesDetectedListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
